### ISSUE TITLE
'from foo import bar' syntax obscures errors in the imported module.

### ISSUE THREAD

**Issue by ioctl79** [brython-dev/brython#357]
Consider the following:

/foo/bar.py:
`import bad_module`

/main.py
`from foo import bar`

This yields a less-than-helpful error: `ImportError: cannot import name 'bar'`

Modifying main.py to read `import foo.bar` gives the correct error (`ImportError: bad_module`).

**Comment by PierreQuentel** [comment]
Hello,

Do you use the latest release or the current development version ?

**Comment by ioctl79** [comment]
Current development.

**Comment by PierreQuentel** [comment]
The commit referenced above should fix the bug. If not, you can reopen the issue.

Thanks !
\- Pierre

**Comment by ioctl79** [comment]
Still a problem as of 0f7deb3c621dfddbff0a25908305a3cf2d50084d

**Comment by PierreQuentel** [comment]
Could you give an example of what you put in `bad_module` ? With
```python
print(x)
```

I now get this in the browser console : 

```
Traceback (most recent call last):
  module ascript line 2
    from foo import bar
  module foo.bar line 1
    import bad_module
  module bad_module line 1
    print(x)
NameError: x
```

**Comment by ioctl79** [comment]
In my test, bad_module does not exist.
