### ISSUE TITLE
Feature Request: Brython Production App Development Pipeline

### ISSUE THREAD

**Issue by glyph** [brython-dev/brython#491]
I've reported some of these issues before, some of them have been closed; but looking at the history of those discussions I don't think it was clear what I was asking for, so I want to try to write up a central tracking issue so that the core team can understand what I wish Brython could do.  The discussion mostly meandered around through performance issues, which, while extremely important, are not really what I care about _now_.

So, here's the problem: I find it very hard to get started developing an application in Brython.  [The official 'deploy'](https://brython.info/static_doc/en/deploy.html) documentation does not actually tell me how to deploy *my* application at all, but rather, just how to load Brython itself into a web page.

First off, as with any Python development tool, I expect to be able to `pip install brython` and start doing something with it.  Even if all this did was put the `.js` file somewhere on my filesystem, similar to the way [certifi](https://github.com/certifi/python-certifi) does nothing but print the location of a `.pem` file, it would be handy having this on PyPI as a way to quickly get started, rather than hunting around for a `.zip` file.

Second, it's not clear how to organize my front-end project.  If I were writing a Python project, I'd write a `setup.py` and perhaps a `requirements.txt` to pin versions.  If I were writing JavaScript, I'd use `browserify` along with `npm install`.  If I'm using Brython, where should I put my files so that `import` works cleanly?  If I want to write a Brython-compatible library, how do I install it?  How do I share my code with other developers?  Right now the only obvious thing is to either write your own web server, and invent some idiom for putting things onto `sys.path` from scratch.

Third, once you have more than a few modules, start-up performance is really, really bad.  Unusably bad, even.  This is a recurring complaint, most recently in #461.  Brython's performance itself is actually perfectly acceptable, if only it could skip the catastrophic load-time hit of transpiling everything from JavaScript every time.  This is related to the second problem, because if we had a way to organize and declare a hierarchy of brython-friendly code that could be imported, and a command to install it and deploy it to the browser, then optimizing startup performance is just a question of translating `.py` files to `.pyc.js` files, and then adding them to a `.vfs` file.  This is also related to the first problem, because if we had `pip install brython`, then in addition to printing the location of `brython.js`, this file could easily also have a `brython compile` subcommand that would produce said `.vfs` file.

Fourth, what does automated testing of a Brython project look like?  Firing up an actual browser is really bad for an interactive red/green/refactor testing workflow, not to mention that it's not clear how to deploy that to Travis-CI.

All together, I want to do something like this.

```console
$ mkdir mybry
$ mkvirtualenv -p `which python 3.5` mybrythonapp
$ pip install brython
$ $EDTIOR setup.py
$ $EDITOR mybry/__init__.py blub.txt
$ $EDITOR web/index.html
$ python setup.py bdist_wheel
$ brython bundle --used-by=web/index.html --used-by=web/about.html --used-by=web/login.html --output web/__brython_cache__.vfs.js --include=dist/*.whl
$ twist web --path web/
$ open http://localhost:8080/
$ brython test 'mybry.test.*'
```

By convention, `brython.js` could then try pre-loading `/__brython_cache__.vfs.js` to prepopulate `sys.modules` with already-compiled-to-javascript modules.  You could also have other `brython` shell commands which would set up symlinks for easy re-loading during development.

The *exact* details of this aren't important though; I just wanted to give one possible example.  There are a lot of ways that this could work.

The current state of the Brython introduction is the same as a Python tutorial that just says "put all your code in one file, you probably won't need two files".

In my opinion this is the *most* important thing that Brython needs to do, in order for mainstream web developers (who, right now, in JavaScript, have advanced build-and-deploy pipelines with grunt and gulp and npm and browserify and a dozen other tools, and in Python, have precompiled wheels and Docker images and so on) to be able to take it seriously for frontend applications that include more than one module.

I hope that this has made it clear what I want from Brython and serves for a good basis for a discussion.

**Comment by jonathanverner** [comment]
> Fourth, what does automated testing of a Brython project look like? Firing up an actual browser is really bad for an interactive red/green/refactor testing workflow, not to mention that it's not clear how to deploy that to Travis-CI.

What I do with my WIP library [circular](https://gitlab.com/Verner/circular) is that I write tests using pytest with stubs for the `browser` module (DOMElement, ...). It might actually make sense to write a more thorough implementation of the `browser` module which could be used in testing. It is on my todo-list, but don't hold your breath. Semester will be starting soon so I will have much less time to contribute.

**Comment by jonathanverner** [comment]
>  if only it could skip the catastrophic load-time hit of transpiling everything from JavaScript every time.

It seems that there was a script to compile python source to javascript using node.js on the server (`scripts/compile.py`) but as of now, it is not functional. I guess it would not be too hard to fix it (mainly stubbing out calls to browser methods in `py2js.js` which are not available in the node.js environment). It is also on my todo-list to look at it.

**Comment by glyph** [comment]
> I write tests using pytest with stubs for the browser module (DOMElement, ...).

How do you *run* pytest under `node.js` though, so you can be sure that you're testing the actual behavior of brython?

**Comment by glyph** [comment]
> It seems that there was a script to compile python source to javascript using node.js on the server (scripts/compile.py) but as of now, it is not functional.

Yes, if this command-line script worked, it would be much easier.

I don't actually want to do this "on the server", just on the build machine, or in my development environment.

**Comment by jonathanverner** [comment]
> How do you run pytest under node.js though, so you can be sure that you're testing the actual behavior of brython?

I don't, I run it using normal Python. I am testing my library not Brython. If Brython behaves differently from Python, I consider that a bug in Brython which should be fixed.

You could, I guess, also use [PhantomJS](http://phantomjs.org/ phantomjs)...

**Comment by glyph** [comment]
Many of Brython's behavior differences are bugs, but (A) they do exist, and it's important to know about them if you're shipping to users, and (B) many of them are *not* bugs, like the fact that the `errno` module isn't present, or that file I/O doesn't work.  In the same way that PyPy and CPython should have the same behavior as much as possible, but that a library which wishes to support both must test on both, there needs to be a way to test Brython applications in a realistic JavaScript environment.

I do know about PhantomJS, and it's probably part of the solution; in fact I started writing a test harness for Brython: https://github.com/glyph/brytly.

**Comment by jonathanverner** [comment]
Fair enough. 

Anyway, I've experimented a bit (before reading your response) with [Selenium](http://seleniumhq.org/) & [PhantomJS](http://phantomjs.org/) and I got  setup which I rather like ([pytest](http://pytest.org/), [pytest-selenium](http://pytest-selenium.readthedocs.io/en/latest/) & [PhantomJS](http://phantomjs.org/)): 

My selenium tests live under `tests/selenium/`. Before running the tests, I start a server which
serves `tests/selenium/webroot/`. My testcases look as follows:

```python
from tests.utils import wait_for_script, selenium_setup_helper

def setup_function():
    selenium_setup_helper(func)

def script_case1():
    """
         <div id='test_div'></div>
    """
    from browser import document as doc
    doc['test_div'].text = "Test content"

def test_case1(selenium):
    wait_for_script(selenium)
    div = selenium.find_element_by_id('spanid')
    assert div.text == "Test content"
```

Each test has two methods: `test_name` and `script_name`. The `test_name` does the testing, the `script_name` runs in the browser.  The `selenium_setup_helper` finds the corresponding `script` method and generates a html under `test/selenium/webroot/tests` with a `<script>` tag containing the code of the `script_name` method and a `<div>` tag containing the docstring of the `script_name` method. The `wait_for_script` calls `selenium.get` to load the page from the server and waits until the script finishes.

I've been able to successfully run these tests on [travis-ci.org](https://travis-ci.org/jonathanverner/circular).

What do you think about it?

**Comment by glyph** [comment]
@jonathanverner This is an interesting approach - and not a bad idea.  It might be nice if you could do a blog post about the full setup (like, how do you get this into Travis?).

But I still think it's a bit heavy-weight for what I want, which is a quick setup for command-line unit test running, so I can get into the test/fix/commit/test/fix loop on a project.

**Comment by olemis** [comment]
@glyph please bear with me for providing you with quick answers . It's 02:00 -5 GMT 

> I expect to be able to `pip install brython` and start doing something with it.

Brython source code is not written in Python . It is more likely that `npm install -g brython` be the command you're looking for.

> If I were writing a Python project, I'd write a setup.py and perhaps a requirements.txt to pin versions.

What prevents you from doing so with Brython-friendly source packages published in PyPI?

> If I were writing JavaScript, I'd use browserify along with npm install.

If you have js libs you can still do so , but alternately it's possible to use distutils commands so as to budle js code within Python-specific packages .

>  If I'm using Brython, where should I put my files so that import works cleanly?

Anywhere , as long as your sys.path contains the URL pointing to your top level modules folder (e.g. virtualenv folder) .

> If I want to write a Brython-compatible library, how do I install it?

Create a virtualenv (for the sake of simplicity, let's assume no inheritance) and use pip, setuptools , ... to install modules as always . Modules and dependencies should be *Brython-friendly* for your app to work correctly, but that's another discussion. IMHO the Brython project should not be prioritizing the creation of specific deploy tools over leveraging the existing (standard) tools available for these purposes. 

There are some optimizations you can make e.g. map path to file type [1]_ , bundle several modules in a VFS archive [1]_ . Since this should not sure of whether there are tools to do so) .

> How do I share my code with other developers?

distutils

> Right now the only obvious thing is to either write your own web server, and invent some idiom for putting things onto sys.path from scratch.

Since recently you can use `<link rel="pythonpath" />` tags [1]_ in web pages . I've not paid attention to command-line execution scenarios , though .

> Third, once you have more than a few modules, start-up performance is really, really bad. Unusably bad, even.

Even after trying file type optimization [1]_ ?

>  if we had (...) a command to install it (Brython) and deploy it to the browser

Commands can be written to deploy Brython onto web servers, not browsers ... I might have misunderstood your phrase.

> then optimizing startup performance is just a question of translating .py files to .pyc.js files, and then adding them to a .vfs file

It's a space vs time constraint . Python code is more concise but takes time to transpile . Transpiled JS code might be huge.

>  could easily also have a `brython compile` subcommand that would produce said .vfs file.

IMHO , the command for doing this should look like `python setup.py bdist --format=vfs` o simplemente `python setup.py bdist_vfs`. Some parameters might help with recursive strategies to bundle and transpile app/lib deps as well.

.. [1] https://brython.info/static_doc/en/import.html

**Comment by olemis** [comment]
@jonathanverner I made some previous attempts to run [the QUnit test suite](https://github.com/brython-dev/brython/blob/master/www/tests/qunit/run_tests.html) on travis-ci and they all failed since the very moment an import statement is executed . I always believed the issue was related to the fact of not launching a web server for accessing source code via HTTP , but I honestly had no time to test my hypothesis . 

It would be nice to make that use case work (preferably without Selenium, so as to avoid hard coupling between test suite code and an external lib) . Would you mind to take a look into that (at your own pace of course) ?

**Comment by glyph** [comment]
> Brython source code is not written in Python . It is more likely that npm install -g brython be the command you're looking for.

No, as a Python developer, I expect `pip install brython` to do _something_; to install a tool that wraps the JS translation, for example.  Running said tool may tell me I need `npm` to do anything useful, of course.

**Comment by glyph** [comment]
> What prevents you from doing so with Brython-friendly source packages published in PyPI?

I can do that, but this doesn't give me any help when I want to *install* those packages on a web page.  What do I do with a requirements.txt that points at six or seven brython-friendly packages?

**Comment by glyph** [comment]
> Anywhere , as long as your sys.path contains the URL pointing to your top level modules folder (e.g. virtualenv folder) .

In that case, the `brython` command-line tool I propose could just run a web server pointed at a combined, flattened version of `sys.path`, which would provide a clear answer to this question.  "anywhere" is the wrong answer, because it requires every application developer to reverse-engineer the interaction between Python's import machinery and Brython's, both of which are under-documented and quite complex.

**Comment by glyph** [comment]
> Create a virtualenv (for the sake of simplicity, let's assume no inheritance) and use pip, setuptools , ... to install modules as always . Modules and dependencies should be Brython-friendly for your app to work correctly, but that's another discussion. IMHO the Brython project should not be prioritizing the creation of specific deploy tools over leveraging the existing (standard) tools available for these purposes.

I totally agree!  And "create a virtualenv" should definitely be the first step.

> There are some optimizations you can make e.g. map path to file type [1]_ , bundle several modules in a VFS archive [1]_ . Since this is specific to Brython we definitely need tools for this but I'm not sure of whether they have already been written .

Aha!  So `make_VFS.py` is the magic script that... sort of... does what I need.  Remember that thing I said about `pip install brython` and you said that brython is not written in Python?  Well, `.py` is not a JavaScript extension ;-)).  In my vision this would be `pip install brython; brython bundle ...`.

**Comment by glyph** [comment]
> Even after trying file type optimization [1]_ ?

Nope! I haven't tried this yet, and I'll be sure to give it a shot soon.

**Comment by glyph** [comment]
> It's a space vs time constraint . Python code is more concise but takes time to transpile . Transpiled JS code might be huge.

My hypothesis is that with a little gzip compression the sizes will be comparable.  But now that I know where that script is, we'll see :).

**Comment by glyph** [comment]
> IMHO , the command for doing this should look like python setup.py bdist --format=vfs or just python setup.py bdist_vfs. Some parameters might help with recursive strategies to bundle and transpile app/lib deps as well.

This sounds great to me!

**Comment by jonathanverner** [comment]
> It might be nice if you could do a blog post about the full setup (like, how do you get this into Travis?).

@glyph: So I've written something up [here](http://jonathan.temno.eu/blog/testing_brython_selenium.html). It is my first technical blog post so the style might be a little rough.  If you have any questions/comments, I'll be happy to elaborate.

**Comment by jonathanverner** [comment]
> It would be nice to make that use case work (preferably without Selenium, so as to avoid hard coupling between test suite code and an external lib) . Would you mind to take a look into that (at your own pace of course) ?

@olemis: I will try that, but it will take me some time.

**Comment by olemis** [comment]
Good . I could help too if I only knew how to setup up this scenario . TBH I almost have no time to take a look into this . If you have the time now , that'd be perfect .

Thanks !

**Comment by jonathanverner** [comment]
@olemis: O.K., so I've started working on this (see #496). Unfortunately, PhantomJS seems to choke on something (chromium works just fine). I don't know how far I'll get, but right now, I have to run off to work.

**Comment by olemis** [comment]
There is a ticket for travis-ci integration , please follow in #234 so that all contributions to this effort be documented in a single place .

**Comment by olemis** [comment]
>> Brython source code is not written in Python . It is more likely that 
>> `npm install -g brython` be the command you're looking for.
>
>
> No, as a Python developer, I expect pip install brython to do something; to install a tool that wraps
> the JS translation, for example. Running said tool may tell me I need npm to do anything useful, of 
> course.

@glyph if you say that `pip install brython` should install the `distutils` extensions implementing `python setup.py bdist --format=vfs` and/or `python setup.py bdist_vfs` plus maybe other tools , then I agree .

**Comment by olemis** [comment]
>> What prevents you from doing so with Brython-friendly source packages published in PyPI?
>
> I can do that, but this doesn't give me any help when I want to install those packages
> on a web page. What do I do with a requirements.txt that points at six or seven
> brython-friendly packages?

I do not understand what *install those packages on a web page*  actually means . Packages are installed in a virtualenv , which is published via HTTP and web pages pull modules/archives from there. The web page only needs a reference to the top-level folder , hence I see no installation step . I might be missing something though .

**Comment by olemis** [comment]
>> It's a space vs time constraint . Python code is more concise but takes time to transpile .
>> Transpiled JS code might be huge.
>
> My hypothesis is that with a little gzip compression the sizes will be comparable. 

@glyph I assume you refer to the web server gzip-ing files transferred to the client browser with the appropriate HTTP headers set . If so, that does not solve the problem . 

> But now that I know where that script is, we'll see :).

I've tried that before and it really makes a difference . Nonetheless I look forward to know more of your results .

**Comment by PierreQuentel** [comment]
I have written programs to precompile all the scripts in the Brython standard library to Javascript, then minify them with uglify.js. Once zipped, the result is only 2.1 MB - I thought it would be much more.

I will publish the scripts once they are a little cleaner.

**Comment by glyph** [comment]
> I have written programs to precompile all the scripts in the Brython standard library to Javascript, then minify them with uglify.js. Once zipped, the result is only 2.1 MB - I thought it would be much more.

Awesome.  However, many programs will not need the whole standard library.  Would you consider adding an option to use something like https://pypi.python.org/pypi/modulegraph/ to determine which modules to include?

**Comment by PierreQuentel** [comment]
I have started something with the built-in module `modulefinder` to list all the modules used by a Brython page, I think I can make it work to generate an application-specific folder with all the compiled JS scripts.

**Comment by glyph** [comment]
@PierreQuentel Awesome. Thank you so much for working on this!

**Comment by PierreQuentel** [comment]
There is a problem with compiled JS scripts : in the current implementation of generators, at run time the generated code uses objects that are initialised at compilation time, and lost afterwards. I will have to change the implementation, this might take some time - it's the most difficult thing in Brython.

**Comment by frastlin** [comment]
Hello,
With compiled Brython code I am looking for something I can insert into another project or use as a package in something like NodeJS.
Looking at the current compiled code at:
http://www.brython.info/tests/precompile.html

it looks like everything is stored at __BRYTHON__.imported[moduleName].
So if I used my scripts in a NodeJS file I would do something like this:
let py = __BRYTHON__.imported
py.main.hello_world()


It feels a little cumbersome, but I think if that is all one needs to do to get their scripts into their javascript project, it just needs to be documented.
I would prefer something that would allow me to specify a project name at compile and within that project name I just reference my modules like:
my_projectname.main.hello_world()
but this is syntactic sugar.

**Comment by PierreQuentel** [comment]
I have finished rewriting the implementation of generators. Brython is not ready for compilation yet, for instance I must find a way to keep track of Python source code for debugging / tracebacks, but this is not as difficult as generators.

**Comment by glyph** [comment]
@PierreQuentel Thanks for the update!  Exciting to see progress.  Are you talking about source maps?

**Comment by frastlin** [comment]
Hello,
This is amazing! I am so happy you are doing this!
Thank you,


Brandon Keith Biggs <http://brandonkeithbiggs.com/>

**Comment by PierreQuentel** [comment]
I have uploaded a first version of [precompiled scripts](http://brython.info/compiled/compiled.zip) for the standard distribution. To test it, clone the Brython repository and uncompress the archive in directory `www`. The directory `www/compiled` should have the js files and subdirectories for all the modules and packages of the distribution.

To use them, call `brython()` with a new option "use_compiled" set, for instance

```
<body onLoad="brython({debug:1, use_compiled:true})">
```

I have adapted the import mechanism to support this option and use the precompiled modules instead of loading the Python source files.

You can test the result by modifying the page __tests/index.html__ and set the option "use_compiled: true" instead of "static_stdlib_import:true".

The good news it that it works :-)

The less good new is that in the first tests I have done, the whole test suite runs in 34" with precompiled scripts, when it takes : 

- 41" without this precompilation step (I measured the time spent in the compilation function py2js in script py2js.js, it takes 7" out of the 41", the figures are coherent).
- 38" for the same test suite executed with brython_dist.js (available with index_dist.html) : it is faster because Python source doesn't have to be loaded by Ajax calls.

A few optimisations can still be done, and the program still loads the modules one by one instead of packing all those required by an application ; but these first results seem to show that unfortunately, the performance will not be that much better with precompilation.

**Comment by glyph** [comment]
> The less good new is that in the first tests I have done, the whole test suite runs in 34" with precompiled scripts, when it takes :

My experience with Brython has been that loading Brython itself and the stdlib were not visibly bottlenecks, so this is not a surprise.  However:

1. It *is* an optimization; a 10% performance improvement is nothing to sneeze at!  Furthermore, you're measuring the _run time_ execution of the entire test suite, but change is optimizing mainly _import time_.  So if the improved performance is entirely at load-time, shaving off 7" (or even 4") is *huge*.
2. The test suite is not a great example; Alex Gaynor's ["your tests are not a benchmark"](https://alexgaynor.net/2013/jul/15/your-tests-are-not-benchmark/) applies here.  We'd have to benchmark exactly what we want to measure with this optimization.
3. This is the major point: as the number of modules scales up, even if the modules are each small, the amount of time to convert them to JS goes up, which is what I was seeing as I was developing a Brython frontend.  On desktop platforms, this extra time is still tolerable, but on mobile it can start to reach upwards into multiple seconds.  Furthermore, the browser can help out with AJAX call overhead, I anticipate that in more non-trivial front-end applications, the load-time benchmark is going to be something significant for interactive performance.
4. This ticket is mainly about having there be a coherent workflow around shipping modules to the browser, not about making it completely optimal; i.e. optimizability, not optimization.  Further load-time optimizations might bring more significant savings, but if everyone is doing their own ad-hoc module loading scheme, the work to apply them will not be worth the savings for any one application.  Whereas if everyone is using the same build and deploy toolchain, they will get future optimizations "for free".

So while you don't see the numbers you're seeing as encouraging, I do :)

**Comment by glyph** [comment]
> the browser can help out with AJAX call overhead

What I mean by this is that the browser can cache the results of GET requests, but it can't cache the results of JS transpilation.  So depending on which caches you're measuring with and how module downloads are organized, you might still see a big import-time hit, but that hit could be much reduced on subsequent loads if the load is of `.js` files directly.

**Comment by kikocorreoso** [comment]
* gzipping individual files could help (but this should occur on the server side).
* 'Uglyfying' individual files could help.

In the past I created custom `brython_dist.js` files only with the needed files for the specific web page I was working using the [`make_dist.py`](https://github.com/brython-dev/brython/blob/master/scripts/make_dist.py) file.

A more fine grained version of `make_dist.py` using `modulefinder` would be great. @PierreQuentel are you working on this? I started some work in the past.

Also, for instance, stuff like [`complex` types](https://github.com/brython-dev/brython/blob/master/www/src/py_complex.js) are rarely useful in the frontend except for specific uses. We should create something that analyzes the code and decide if some stuff can be discarded, e.g., `py_complex.js` in the final `brython_dist.js` for a specific web page.

**Comment by PierreQuentel** [comment]
@kikocorreoso 
I have tried to use `modulefinder`, but it fails (obviously) with modules written in Javascript. I am trying another approach, which is to run the application and then get the keys of object `__BRYTHON__.imported` to know which modules the application needs.

**Comment by kikocorreoso** [comment]
@PierreQuentel I am thinking even in something more aggresive in order to reduce the size of the files.

For instance, built-ins not used in the whole 'app' and dependencies (e.g., complex, super, hex,...) could be removed, types not used (e.g., complex) could be removed,..., py2js (very heavy right now) could be removed as it would be an ahead of time transpilation,... so you will end up just with the useful stuff needed by the scripts.

Of course this is not easy nor simple.

But, at least, I have an internet connection since yesterday and I can be operative again.

Let me know if it could be useful a skype/hangout to check the possibilities.

**Comment by olemis** [comment]
If you schedule the Skype/Google hangout then count me in . Just let me know of the exact time.

--
Regards

**Comment by glyph** [comment]
> I am thinking even in something more aggresive in order to reduce the size of the files.

I would like to please caution you to _not_ do these sorts of optimizations until there is a working pipeline of some kind.

Before you start in on specific _optimizations_, there should be an _optimizable_ pipeline.  If the workflow is (let's say) `python setup.py bdist_js`, and everyone sets up their CI to work with that command, and brython becomes a popular tool, adding an optimization to `bdist_js` at that point will benefit everyone.  However, if we _block_ on creating that pipeline and getting everyone to build up all of the ancillary tooling (web server and server-side framework integration, continuous integration patterns, documentation) until all the possible awesome optimizations are already implemented, then there will be more and more ad-hoc workflows that projects have for shipping their Python / JS code into the browser.

More importantly, there is a common antipattern in the python packaging ecosystem (which at least py2app, py2exe, pyinstaller, and cx_Freeze have fallen victim to) where the tools makes everything super optimal by default at the expense of correctness.  From the perspective of a tool author, this proposition seems super attractive; just don't do {this really weird seeming thing} in your code, and everything will be 50% faster / smaller / whatever.

The problem is, if I have a medium-sized project that depends on a dozen libraries I didn't write, {this really weird seeming thing} (usually a dynamic import) is going to happen in at least 2 of them, for some good reason.  The manifestation of this problem is always going to be a `NameError` or `AttributeError` or `ImportError` at runtime, coming out of some library I don't really understand or control.  This is _extremely_ hard to debug, and most people just give up and switch to a toolchain (in Brython's case, something like Angular or React) where the ecosystem that exists behaves in a predictable way.

So, it's important that the workflow be:

`python setup.py bdist_js` → working app

hooray, user feels great, but hey it's a little slow

`python setup.py bdist_js --super-aggressive-optimizations` → broken app

at this point they can decide if they _really want_ the optimizations that they're going to get, or maybe fall back to `--medium-aggressive-optimizations` to see if that works.  But if they can't get the initial positive experience of "everything just works, even if it's just a little sluggish" then they'll never get to step 2.

**Comment by kikocorreoso** [comment]
@glyph You are right.

The main idea is to start with the easiest path and then continue iterating in a correct way and letting things ready to allow iteration instead of a rewrite in the future.

**Comment by PierreQuentel** [comment]
Yesterday I pushed a new script, __find_modules.py__ in directory __scripts__. It takes an HTML file and scans all the Brython scripts it includes (recursively) to list all the modules and packages needed by the page.

It is a first version, only tested on very few examples. The next step will be to generate the compiled version of the modules / packages.

**Comment by PierreQuentel** [comment]
With an improved version of __find_modules.py__ I could test the generation of precompiled JS scripts for a Brython file, namely __gallery/kanban.html__. Much to my surprise, I found that even for such a simple script, there are no less than 123 modules to compile ! Even __unittest__ is required, because of this requirement chain : 

- kanban.py requires time
- time requires _strptime
- _strptime requires locale
- locale requires collections
- collections requires heapq
- heapq requires doctest
- doctest requires unittest

When I say "A requires B" it means that somewhere in the code of A there is "import B", even if the page kanban.html never uses the block that performs this import - but it's impossible to know in advance.

The size of these 123 modules is 2,405,273 bytes uncompiled (more than 2/3rds of the size of brython_dist.js) and 18,049,676 bytes once converted to Javascript.

For another simple page, __clock.html__, the figures are 2,398,397 and 18,063,684 bytes.

To get these results :
- edit __scripts/find_modules.py__ to select the path of the Brython page line 236
- running the script generates a text file __imports.txt__ in directory __www/gallery__
- load the page __/gallery/compiler.html__ : it reads __import.txt__, loads the source file of all scripts and converts them with `javascript.py2js`. In the browser console you see the size of uncompiled and compiled results

My conclusion at this stage is that because of the complex chain of imports, most Brython pages will require a significant part of the standard distribution. Selecting only the required modules does not bring much improvement and is more complex (and error-prone) than deploying brython_dist.js and/or the complete set of precompiled files.

**Comment by glyph** [comment]
> My conclusion at this stage is that because of the complex chain of imports, most Brython pages will require a significant part of the standard distribution. Selecting only the required modules does not bring much improvement and is more complex (and error-prone) than deploying brython_dist.js and/or the complete set of precompiled files.

I can see back on September 10 I made a comment about not including all of the standard library.  I apologize; that suggestion was a premature optimization.

The reason I recommended modulegraph (or similar) is that I anticipated such an optimization would be necessary for any distribution of libraries which _normally_ run on PyPy or CPython but are intended to have a Brython-compatible subset; attempting to JS-compile all of the modules in those libraries might run into issues.  So I figured if we're going to need it anyway maybe applying it to the standard library.  But by saying that, I myself fell into the trap that I was trying to warn you about, which was focusing on a specific optimization rather than the optimizable pipeline.

To be clear: the part I care the most about here is the part that bundles up _my own code_, and that of _the libraries that I have `pip install`ed and imported in my code_, not the brython standard library.  If a necessary complement to that is attaching `brython_dist.js`, that's fine; the brython interpreter itself is a certain level of fixed overhead I need to accept, and if the whole standard library needs to come with it it's not a big deal.  Depending on the site, it might actually be better / lower overhead to cache all of `brython_dist.js` anyway, because every page can share the same cached blob.

**Comment by glyph** [comment]
> If I understand correctly, this means that there should be another bundled file (other than py_VFS.js, but with the same structure) that would hold all the modules and packages in the Brython page folder (your own code) and in Lib/site_packages, which is where third-party modules are installed (the libraries that you have pip-installed).

Roughly, yes.  However, this separation is somewhat of an implementation detail.  I think it's important to create a somewhat flexible structure based on some inputs from the user, so that there is flexibility to optimize in different ways in the future.  For example, as mentioned previously, on some sites (those with lots of small scripts that re-use the same functionality) it's best to optimize by sharing a large single-asset library bundle between all the small scripts, even if it's "too big" for any one page, because it's a large shared cache; on other sites (those with one big single-page application) it's much better to crush everything into a single whole-application bundle.

So we need an "input" interface (what does the developer specify about their code?) and an "output" interface (what do they load in their HTML, what do they ship to their static asset server).

**Comment by glyph** [comment]
> We could even have .bundle-ignore files in all these folders to reduce the size of the bundled file ; the application developer would have to write them with all the paths that he is sure won't be used by the application.

This would be part of the "input" interface, but if I understand what you're saying: you're saying that each folder would have a listing of .py files not to translate that are in that folder?  I believe this is a flawed way to do it, since it puts the responsibility for pruning dependencies in the wrong place.

If I am shipping a library to PyPI, which files can be excluded from that library without breaking it is dependent upon two things.  The first is that I (the library author) might have some files which just can't ever be parsed by brython, due to limitations on brython or dependencies on operating system functionality.  Those I might want to drop a `.bundle-ignore` (or similar) file into the folder that I own, which is `site-packages/the_library`, to say "don't ever include these".

However, which _other_ files can be used to optimize a particular application's usage of my library is _the application's_ responsibility.  You (the application author) might import my library, which contains 100 modules, but only import 6 of them.  You should be able to put the "bundle-ignore" information into the directory that _you_ own (i.e. `site_packages/your-application`) that says to ignore stuff from _my_ library, when building the bundle for your site / application.

**Comment by glyph** [comment]
In setuptools right now, the "input" interface is an "entrypoint"; in my `setup.py`, I tell the packaging system that I have a `console_script` that is a Python function which should be invokable by a command-line script.  Having something similar for Brython would be nice.  For example, an entry-point-like object that says "here's my HTML files, their `<script>` tags import some modules, make all those modules importable".  The bundler could then examine the HTML files and kick off the discovery process with the modules they import, or you could go even simpler, and say that there's a requirements.txt, all modules from those requirements should be translated except those in an "excludes" list. 

Here's my proposal for the "output" interface.  Rather than separate commands to generate separate pieces of this, a directory full of JS files, perhaps with a `brython.js` at the top of it.

Modifying my original proposal just a little bit, let's get rid of the direct consumption of wheels; let's assume that you have `pip` install all of your dependencies already.

The way that the application consumes this output interface is that you run (going back to my original example):

```console
$ brython bundle --used-by=index.html --used-by=about.html --used-by=login.html --output my-fun-app
```

In each HTML file, you have a `<script>` tag just like today, except instead of this:

```html
<script type="text/javascript" src="src/brython.js" />
```

you have

```html
<script type="text/javascript" src="my-fun-app/brython.js" />
```

The `brython` top-level function contained in this generated `brython.js` can then examine the context in which it's loading, which HTML file is loading it, and load whatever `my-fun-app/*_vfs.js` dependencies that it needs to.  My point about this structure, however, is that the build pipeline today would be:

- pick a folder name (in the above case, "my-fun-app")
- `pip install brython` (Yes, I know that this might just immediately say "btw make sure you have `npm` installed too or the `brython` command won't work; that's fine)
- run `brython bundle --output my-fun-app` to get a basic `brython.js` in my output folder; add that `brython.js` to all your HTML files
- as you add dependency modules, `pip install` those dependencies (either from libraries, or doing `pip install -e ...` on your own project) into the environment where you have the `brython` tool installed, and then `brython bundle --output my-fun-app` again
- as you upgrade to more sophisticated CDNs, just make sure that the contents of `my-fun-app` are available at the same URL somewhere, and that the HTML you're writing loads from there.

This gives the `brython bundle` tool the flexibility to change exactly what it puts into that directory; it could generate one gigantic `brython.js` with your whole app in it, it could generate one `.pyc.js` for every single library module... whatever.  I don't care :-).  All of this can be optimized and changed in future versions, but my application stays the same, and I don't need to change anything about how I'm using brython, just `pip install --upgrade brython` to get newer, faster, better versions.

**Comment by glyph** [comment]
This is a recurring theme, but since some of my comments are kinda long, I should probably put this sentiment to stand alone:

Optimizing load latency is a complex problem that will certainly see many future iterations and different implementation strategies. One strategy will not work for all applications; different applications have different characteristics.  Therefore, the important thing is not to figure out the one correct strategy up front; that's impossible.

The important thing is to allow people to start writing big Brython applications today, and provide them with future-compatible tooling which, when new and exciting optimization strategies are discovered, they can take advantage of those new strategies _without_ changing anything about their code, their build system, or their deployment pipeline.

The most important reason to have such a pipeline in place is to allow for the development of 3rd-party libraries and add-ons for Brython which make it easier to write apps using it.  If I want to write a JavaScript application today, it is trivial to grab off-the-shelf modules using `npm`, and get them integrated into my optimized workflow using `webpack` or `browserify`.  Brython starts from a nicer place than JavaScript - the language is better.  But the advantage of the better language is rapidly overcome by the disadvantage of needing to either write all the code yourself, or invent some new non-standard way to pull in code that other people wrote on every project.

In other words, the optimization I'm trying to focus on in my problem description is to optimize for _community_.  Optimizing for load time is secondary to that. :)

**Comment by frastlin** [comment]
Hello,
The use case I am looking forward to is using Brython as a library in my JS code. That way I can write the complex stuff in Brython, then pull those scripts in my Javascript. So I can do something like:
<script src="my_fun_brython_app.js"></script>
<script>
var app = new my_fun_brython_app("localhost:3000")

app.contact_server("Hello server")
</script>

As well as bundling it like Glyph said above. I want the speed and elegance of brython but not be locked into Brython for everything. I want to have two way communication between the two.

**Comment by PierreQuentel** [comment]
In the latest commits I have added a folder __/setup__ to generate a distribution of Brython for CPython users. The process is as follows : 

- run the script __/setup/data/prepare_setup.py__ : it generates a script __brython_stdlib.js__ which is almost the same as __brython_dist.js__, but the script takes into account a file __.bundle-ignore__ at the root of __/src/Lib__ which specifies the scripts to ignore in the bundle. __brython_stdlib.js__ is stored in __/setup/data/lib__. __prepare_setup__ also copies __brython.js__ in this folder
- then generate the Brython distribution by the usual `python setup.py sdist_wheel` (__setup.py__ is in __/setup__)
- install it with `python setup.py install`
- to create an environment for Brython development, create a folder in the file system, and in this folder run `python -m brython`. This will install a set of files and subfolders, among them `server.py` (starts an HTTP server) and `index.html`, a very basic page that loads __dist/brython.js__ and __dist/brython_stdlib.js__.

This is still very experimental, but it's a step towards an easy installation of Brython with `pip install brython`. Feedback and improvements are welcome !

**Comment by PierreQuentel** [comment]
@frastlin Brython is designed to be able to use Javascript libraries, but not the other way round, or at least in a very limited way, because the objects created by Brython are generally not usable directly in Javascript.

Example : 
```html
<script type="text/python">
from browser import window
x = {'a': 1}
window.x = x
window.init()
</script>

<script type="text/javascript">
function init(){
    console.log(x)
}
</script>
```

You might expect that the `x` in `init()` is the Javascript object `{a: 1}`, but it's not the case : the function prints
```Object { __class__: Object, $numeric_dict: Object, $object_dict: Object, $string_dict: Object, $str_hash: Object, length: 0 }```
which reflects how Python dictionaries are implemented in Brython. The types are too different to even try a conversion: the dictionary `{1: 2, "1": 3}` cannot be converted unambiguously to a JS object.

**Comment by PierreQuentel** [comment]
With the latest commits on the Github repo, the development pipeline is currently as follows :

1 - create a CPython package "brython" with `python setup.py bdist_wheel` in folder __/setup__
2 - install it : `python setup.py install`

_NB : these first 2 steps will be replaced by `pip install brython` once the brython package is uploaded to PyPI_

3 - create an empty folder ; in this folder, run `python -m brython --install` : this installs a minimal Brython distribution, structured this way :
```
(root folder)
    .bundle-ignore
    index.html
    server.py
    + dist
        brython.js
        brython_modules.js
        brython_stdlib.js
```        
The basic Brython page, __index.html__, loads __dist/brython.js__ and __dist/brython_modules.js__. Initially, __brython_modules.js__ is the same as __brython_stdlib.js__ (the Brython standard library).
    
4 - develop a Brython application, including modules or packages in the root folder of the distribution. During development, these modules are imported with Ajax calls. At some time in the development process, the file structure may look like :
```
    .bundle-ignore
    index.html
    server.py
    users.py
    utils.py
    + app
        __init__.py
        records.py
        tables.py
    + dist
        brython.js
        brython_modules.js
        brython_stdlib.js
```

5 - once in a while, especially when preparing the application deployment, generate a new version of __brython_modules.js__ by `python -m brython --update` ; this will include __brython_stdlib.js__ and the application-specific modules and packages. If some of the modules in the root folder don't have to be included in __brython_modules.js__, they must be added to __.bundle-ignore__.

In the example above, __brython_modules.js__ will include the minified source code of modules `users, utils, app, app.records` and `app.tables`.

After updating, all the modules are loaded from __brython_modules.js__ so there is no Ajax call. This means that to deploy the application, _only 3 files will be needed_ : 
```
    index.html
    + dist
        brython.js
        brython_modules.js
```

6 - If necessary, __brython_modules.js__ can be reset to __brython_dist.js__ by `python -m brython --reset`

There are still missing features - including packages loaded by `pip install`, a tool to create a distribution for the application, and if possible a way to reduce the size of the distribution (maybe using the script __find_modules__ referenced above after all).

**Comment by glyph** [comment]
Following these directions, I accidentally registered the 'brython' package since nobody had previously claimed it (with `twine upload`) so 401162f74ad01336f1bf65156f085ce2ca76bf46 is now on PyPI as `3.2.9`: https://pypi.python.org/pypi/brython/3.2.9 

However, it was not my intention to steal the package index entry (I thought I was pushing it to my local devpi server, and that if I were misconfigured it wouldn't work because someone else would have claimed the package on PyPI), so if you will let me know your PyPI name I will add you to the project.  Since I have access now though I'm happy to do releases to PyPI as necessary :).

**Comment by glyph** [comment]
As uploaded it seems that the wheel doesn't work.

```
$ python --version
Python 3.5.2
$ pip install brython
Collecting brython
  Downloading http://127.0.0.1:3141/root/pypi/+f/88c/cae353d4a2a60/brython-3.2.9-py3-none-any.whl
Installing collected packages: brython
Successfully installed brython-3.2.9
$ mkdir empty-dir
$ cd empty-dir/
$ python -m brython --install
Installing Brython
Traceback (most recent call last):
  File "/Homebrew/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/Homebrew/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/glyph/.virtualenvs/tmp-7e02aafeb23365bd/lib/python3.5/site-packages/brython.py", line 37, in <module>
    for path in os.listdir(os.path.join(src_path, 'dist')):
FileNotFoundError: [Errno 2] No such file or directory: '/Users/glyph/.virtualenvs/tmp-7e02aafeb23365bd/lib/python3.5/site-packages/data/dist'
```

**Comment by PierreQuentel** [comment]
I'm afraid I forgot to mention the first step : running __/setup/data/prepare_setup.py__ ; it is this script that creates the __/dist__ directory.

Thanks for this first release on PyPI ! My login is quentel.

**Comment by glyph** [comment]
@PierreQuentel I've added "quentel" to the project; you should see yourself as an owner and be able to upload to https://pypi.python.org/pypi/brython - remember to use https://pypi.python.org/pypi/twine to be sure to do it securely :)

**Comment by PierreQuentel** [comment]
Thanks ! I will do it tomorrow, it's time to go to bed here ;-)

**Comment by glyph** [comment]
@PierreQuentel Thanks! The version you created also seems to _work_, which is a plus :)

**Comment by glyph** [comment]
@PierreQuentel Okay, this is getting _really_ close to what I want :-D.

It seems like the main missing piece at this point is some way to get `pip`-installed modules to be compiled as well.  I think it's fair to say that a brython project can just have a `requirements.txt` to say which modules ought to be installed (this can include `brython` itself, after all, since when you start it's not installed), so the `python -m brython` tool does not need that part for now.

For starters, what about a `.bundle-include` file that just has module names that need to be importable?  Actually, given that the example exists now, maybe I can just do the PR myself instead of bothering you :).  Would you mind if I added Twisted to brython's `setup.py` so that we could have a production-quality / SSL capable / programmable webserver on the server side?  In order to make `sys.path` be importable I'll need to modify `server.py` quite extensively and I'd rather use something that makes that easy.

**Comment by kikocorreoso** [comment]
Thinking in the way it is created the bundle, the distribution of the project can be pretty similar to, e.g., a flask app:

```
    .bundle-ignore
    index.html
    server.py
    users.py
    utils.py
    + app
        __init__.py
        records.py
        tables.py
    + dist
        brython.js
        brython_modules.js
        brython_stdlib.js
```
If the flask/whatever project is pretty big you would have to add a lot of stuff in the `.bundle-ignore`. Would it be useful to add a '.pyb' extension to avoid conflicts with 'real' python files and do this process more manageable for users?

**Comment by glyph** [comment]
> Would it be useful to add a '.pyb' extension to avoid conflicts with 'real' python files and do this process more manageable for users?

The whole point of this pipeline is to make it possible to deploy the same python and server-side and client-side.  A different extension for Python files will make this impossible.

Instead, if the `.bundle-include` file (or whatever mechanism we use to allow it to say "add this stuff on `sys.path` and make it importable) includes any server-side modules, they can be installed with `pip install -e`, and the package can be organized like this:

```
+ setup.py
+ client
    .bundle-ignore
    .bundle-include
    index.html
    server.py
    users.py
    utils.py
    + dist
        brython.js
        brython_modules.js
        brython_stdlib.js
+ server
    + app
        __init__.py
        records.py
        tables.py
```

**Comment by PierreQuentel** [comment]
@glyph 
In the current version of the brython package there is a server, but I don't think it's really useful, the HTML page works very well without a server, and when uploaded it's the site server that is used. Anyway I'd rather not add a dependancy to a specific server in setup.py.

As for the additional modules, I'm not sure to understand what .bundle-ignore would do. What would be in it, and if it's a reference to these modules, how would they be added in the directory where you run `python -m brython --install` ? If you can do a PR that would be great.

**Comment by glyph** [comment]
> In the current version of the brython package there is a server, but I don't think it's really useful, the HTML page works very well without a server, and when uploaded it's the site server that is used. Anyway I'd rather not add a dependancy to a specific server in setup.py.

Actually, it occurs to me that adding a server-specific dependency will make it too hard to use features like CDNs, so let me think about how to do this from within the `brython` tool.

> As for the additional modules, I'm not sure to understand what .bundle-ignore would do. What would be in it, and if it's a reference to these modules, how would they be added in the directory where you run python -m brython --install ? If you can do a PR that would be great.

`.bundle-include`, you mean?

Let's say you did `pip install mybrowserlib`, which installed the following:

```
+ site-packages
    + mybrowserlib
        __init__.py
        a.py
        b.py
        c.py
```

If your browser app used `mybrowserlib` and `mybrowserlib.c` but not `mybrowserlib.a` or `mybrowserlib.b`, you could add a `.bundle-include` to your project that does

```
mybrowserlib
mybrowserlib.c
```

and then `python -m brython --install` would generate a `brython_modules.js` containing the translated versions of `mybrowserlib/__init__.py` and `mybrowserlib/c.py`.

Nevertheless I will see if I can do a PR sometime next week.

**Comment by PierreQuentel** [comment]
I have made a few changes to the package : 

- removed __server.py__
- put the brython files (__brython.js__ and __brython_modules.js__) in the same folder as __index.html__ : I don't think it's useful to have 2 levels, and the name "dist" for the folder was not very relevant. I expect users to install the package in a folder called "brython" so they would insert _/brython/brython.js_ in their scripts, not _/brython/dist/brython.js_.
- I have worked on __index.html__ to include a few examples of what one can do with Brython. Do you think it's a good idea ? Or should this be included as a "getting started" section in the documentation pages ?

**Comment by jonathanverner** [comment]
> I expect users to install the package in a folder called "brython" so they would insert /brython/brython.js in their scripts, not /brython/dist/brython.js.

I am not sure about this. When writing a web app, I would most likely only deploy the javascript files not the whole Brython package, so it might be a bit easier to have the js files in a separate directory.

> I have worked on index.html to include a few examples of what one can do with Brython. Do you think it's a good idea ? Or should this be included as a "getting started" section in the documentation pages ?

I think this should be included in the "getting started" section. Putting it **also** in index.html makes sense, though.

Just my thoughts...

**Comment by PierreQuentel** [comment]
@jonathanverner 
The "whole Brython package" only has 4 files, among which 2 (index.html and .bundle-ignore) are not really required to run Brython, this is why I think it's better to put the 2 main files (brython.js and brython_modules.js) in the main folder.

**Comment by glyph** [comment]
@PierreQuentel The way I think of it, it's not the "main folder" so much as the "selected brython output folder", so it makes sense to eliminate the `dist/` subdirectory and put everything at the top level.  If someone wants to put it in a subdir within their project they are welcome to run `brython` somewhere else :).

Can you do a new release that includes this change?

**Comment by PierreQuentel** [comment]
I have published version 0.0.4 of the brython package, with 2 changes : 

- with `python -m brython --update`, if there is a file __.bundle-include__ in the folder, only the modules in this list are included in __brython_modules.js__
- the object `__BRYTHON__` supports a new method `imports()` that opens a popup window with the list of all the modules currently imported (the same as `sys.modules`)

With these features, the workflow to minimise the size of __brython_modules.js__ would be :

- run the application in the browser
- open the browser console and execute `__BRYTHON__.imports()` on the console command line
- copy/paste the modules list in file __.bundle-include__
- run `python -m brython --update`

This works in the few tests I made (some of the examples in the gallery), with __brython_modules.js__ limited to a few 10 kbs instead of 3.4 Mb for __brython_stdlib.js__.

**Comment by glyph** [comment]
Hello Brython developers!  Just checking in - how is this doing?

**Comment by PierreQuentel** [comment]
I think we have gone as far as possible in this direction : installing Brython with pip, and building a bundle of the Python scripts needed by an application. The work on this issue has shown that precompiling Python scripts into Javascript is not possible because of the size of the compiled script. I can't think of other improvements for the moment.

**Comment by glyph** [comment]
The main improvement I can think of is for Brython to have a clear, detailed tutorial explaining all the steps you laid out in [this comment](https://github.com/brython-dev/brython/issues/491#issuecomment-266066692).  For example, I still do not know what "the modules list" refers to in this case.  The small documentation fragment I see here does not really explain how to do it from start to finish.  Do I need to write a `setup.py`?  A `requirements.txt`?  A `package.json`?  How do I indicate Python dependencies? Javascript dependencies?

Another big improvement would be to include a server app that would automate this deployment process (perhaps by using Phantom or Nightmare, or even just by using the `webbrowser` built-in python module).

Another would be to integrate this into some other deployment workflow - I don't know a lot about client-side workflows, but perhaps webpack would be the main example of this?

Another would be to integrate `.bundle-include` into a setuptools extension or other piece of more standard metadata.

But the major important thing is to have a document that you can point people at when they ask "how do I write a client-side Python application using Brython, test it, and ship it to production".

**Comment by PierreQuentel** [comment]
_Cent fois sur le métier remettez votre ouvrage..._

The current solution to generate the __brython_modules.js__ file is not what I am the most proud of... So I have resumed work on this and now have a different, and hopefully better, solution.

1. `python -m brython --install` installs the basic Brython files in a new application directory.

2. The developer writes HTML pages and Python scripts to develop the application

3. The new command-line option `python -m brython --make_dist` executes the following tasks : 

 - generate __brython_modules.js__ by parsing the code in all Brython scripts (forget __.bundle_include__ !). This is done in a new module in the Brython repo, [/setup/list_modules.py](https://github.com/brython-dev/brython/blob/master/setup/list_modules.py) ; it is based on an AST visitor to recursively detect imports
 - copy the application files in a subdirectory called `__dist__`
 - in this directory, for HTML pages, `<script src="/path/to/brython/brython_stdlib.js">` is replaced by `<script src="/path/to/brython/brython_modules.js">`
 - the user is asked to enter basic setup information : application name, version, author, author email, url. This information is stored in a file __brython_setup.json__ to avoid having to enter the information each time a `--make_dist` is run
 - this information is used to generate a __setup.py__ script, and another script called like the application name (eg __myapp.py__)

4. from the __\_\_dist\_\___ subdirectory,  running `python setup.py sdist` and `python setup.py install` installs the package `myapp`. This is done manually in case the developer wishes to edit or add information in __setup.py__. _The package is an ordinary Python package and can be distributed through PyPI and pip._

5. running `python -m myapp --install` installs the application files (HTML pages, __brython.js__, __brython_modules.js__, Python scripts, etc.) in an empty directory

A first version exists in the current development version. It's certainly not complete but I wanted to have your and other people's feedback before going on.

**Comment by glyph** [comment]
> Cent fois sur le métier remettez votre ouvrage...

As a (poor) student of french, could I ask for a translation of this? Is it an idiom? Google translate makes a bit of a mess of it.  (I think I get the gist with "cent fois" though ;))

> So I have resumed work on this and now have a different, and hopefully better, solution.

\o/

> *The package is an ordinary Python package and can be distributed through PyPI and pip.*

This sounds AMAZING and I am disappointed that I will probably not have time to try it out soon.  I will make a note of this and give you feedback as soon as I can though!!!

**Comment by PierreQuentel** [comment]
The sentence (written by a XVIIth century poet, originally about the art of writing) has become an idiom meaning "resume work on the same topic over and over again until it's what you really want". I'm far from 100 times so I look forward to your feedback ;-)

**Comment by glyph** [comment]
Thanks for the translation! The problem is that nothing wants to translate the word "métier" as anything but "job" or "work" which is weird.  Once I understood it can also mean "loom" or "frame" it made much more sense :)

**Comment by 602p** [comment]
Hey all.

I've been writing a webapp with Brython, and enjoying it very much as opposed to JavaScript. However, I've been hitting the same load time issues that motivated this issue. I'd be interested to understand what the current state of precompliation/bundling support is in brython.

Having installed the latest version of the package `brython` in my local environment, I have succeeded in bundling the files of my app together into a `brython_modules.js` file using the `__BRYTHON__.imports()` scheme (and this seems to prevent the searching for them.) However, this isn't what I was hoping for, because a massive amount of time still seems to be spent in the compilation step - over a second is spent internal to the call to `brython()` after all of the sources have been loaded.

What is the current state of precompilation? I see some info in here on tooling, but I can't seem to get a coherent picture (additionally, `python -m brython --make_dist` does nothing on my machine - the module does not seem to take that option.) I'd very much like to see an option to somehow build a cache of the compiled JS output along the lines of `__BRYTHON__.imports()` that I could then minify and dump into a file on the server, and then serve that instead of `brython_modules.js`. I understand the worry that this file would be absurdly large, but looking at the output of running `brython(10)` the sum size of all used modules' compiled JS versions (not yet minified) is less than 3 MB - I'd much rather have a one-time cache-able 3MB download than a 2 second lag every time I open the page.

Is this a possibility?

**Comment by jonathanverner** [comment]
In theory, it should be possible, but at the moment I am afraid you are on your own. There used to be a node script for precompiling python to js but at the time I was testing it, it didn't work. You might have more luck today (while working on supporting webworkers we needed to make sure brython doesn't automatically assume it is run in the browser, e.g. accessing document etc.)...

Another option would be to use python to drive a headless chromium browser. The python script would serve a page with the code you wanted compiling and a script which would submit the compiled javascript back to the python server at which point you could write it out to a file.

**Comment by 602p** [comment]
Thanks for the response :)

I don't think I'll try to set up Node - I'm here to get away from writing JavaScript after all...

Headless (or regular - this would probably be something I did before a "deploy" of the app only) chrome would work fine - my struggle is just figuring out how to set up the output of brython's compiler as something that can then be loaded thru the import mechanism. Are there docs on how one goes about writing a JS module? It seems like it's supported (`<something>.js` will show up in the search paths for `import something`) but not really mentioned in the docs. Time for some reading of the import implementation!

I may do some hacking on my own to try to get something like this to work - although I'd prefer to see a workflow including something like the proposed `brython bundle` in the future!

**Comment by jonathanverner** [comment]
As far as internal documentation goes, there is [How Brython Works](https://github.com/brython-dev/brython/wiki/How%20Brython%20works). However, imports are not mentioned there. I think the place to look at is [py_import.js:194](https://github.com/brython-dev/brython/blob/0bfc056619f1447a1fd9032dac0b58bdc35e1201/www/src/py_import.js#L194)

**Comment by glyph** [comment]
I'm just cheering from the sidelines here, but thank you @602p for a clearly-articulated restatement of the problem :)

**Comment by glyph** [comment]
Playing with brython a bit again today, I did `pip install brython` and messed around with `python -m --modules`, and it sort of looks like it works!  Unfortunately the very first library I tried to add with `--add-package` didn't work, as documented in #766 .

**Comment by PierreQuentel** [comment]
@glyph Today I published a new version of Brython in PyPI and saw that you were mentioned as owner of the package. I had forgotten why, and withdrew your name ; it's just now, reading this thread again, that I realize that it was you who originally created the package. Do you want me to add you again as owner ?

Anyway, this new version (3.6.2), and the previous one (3.6.0) which I had to remove from PyPI because of a bug in setup.py, should solve one of the problems mentioned in this issue : a precompiled version of the scripts in the standard distribution is now stored in an indexedDB database. This improves the loading time of scripts that use modules from the stdlib (except the first time it is run, because the precompilation has to be done and stored). I have explained how this works in the [How Brython Works](https://github.com/brython-dev/brython/wiki/How%20Brython%20works) section - it's not for the faint-hearted ;-)

**Comment by glyph** [comment]
@PierreQuentel I'm fine being removed! I was registering on PyPI as a way to encourage you to maintain it, so as far as I'm concerned, things are good :).

**Comment by glyph** [comment]
Just checking in on this - it seems like the state of things has advanced considerably, but it's still not as simple as dropping in to a webpack pipeline.  Where do things stand today?

**Comment by glyph** [comment]
@jonathanverner :

> @glyph: So I've written something up [here](http://jonathan.temno.eu/blog/testing_brython_selenium.html). It is my first technical blog post so the style might be a little rough. If you have any questions/comments, I'll be happy to elaborate.

Sorry for the *very* long delay on the request for comment, but I just had a minute to read your blog post and it was great!  I'm sad to see that Circular has not received much maintenance in the meanwhile.

The one thing that I would love to see as an add-on to this is really just how small utility library authors (I'm thinking, in particular, of `hyperlink` and `attrs`) can set up CI to be compatible with brython, and selenium seems pretty heavy (particularly, the need to write HTML pages that include brython and kick things off, so that there can be something on the page to test).  Do you have any experience with more "pure python" testing, i.e. tests for code that wants to run on both frontend and backend?

**Comment by aehlke** [comment]
Has this gotten any better the last 2+ years? Thanks

**Comment by jonathanverner** [comment]
Unfortunately, not at all. Real life intervened and I didn't really have time for Brython in the past four years :-(

**Comment by glyph** [comment]
> Unfortunately, not at all. Real life intervened and I didn't really have time for Brython in the past four years :-(

Sorry to hear that :-(. A very identifiable feeling.
