### ISSUE TITLE
bytes are not working properly

### ISSUE THREAD

**Issue by kikocorreoso** [brython-dev/brython#98]
The following:
```python
print(b'\xfc')
```
in Brython returns
```
b'\xc3\xbc'
```
while in Python3.4 returns
```
b'\xfc'
```

`int.from_bytes` returns incorrect results in some cases.

This issue affects issue #97.

**Comment by kikocorreoso** [comment]
@PierreQuentel @earney Please, could you have a look to #96 #97 as you are the coders of *py_bytes.js*, *py_int.js* and the ***random*** module? I'm a little bit lost with the details.

Thanks in advance.

**Comment by PierreQuentel** [comment]
Kiko,

This bug seems to be fixed with the latest commits by Billy. Can we close the issue ?

**Comment by kikocorreoso** [comment]
I think the bytes literal representation `b'xxxxxxxxxx` is not well translated to `bytes` or `bytearray`.

For example, the following (from the docs, it is just an example, https://docs.python.org/3/library/stdtypes.html?highlight=int.from_bytes#int.from_bytes):
```python
tmp = b'\xfc\x00'
```

Is translated to a `bytes` class with the following array inside: [195, 188, 0]
And the representation is transformed to: `b'\xc3\xbc\x00'`

If I translate to int using `int.from_bytes(b'\xfc\x00', 'big') I should obtain `64512` but with Brython I'm obtaining `3949568`.

I'm digging in the code of ***py_bytes.js*** to understand how it is implemented.

Please, could you confirm it his is a bug or I'm worng? If it is a bug just let me dive a little bit more to fix it. I'm learning more about Brython with it. I arrived to here (https://github.com/brython-dev/brython/blob/master/src/py_bytes.js#L430) where I think it is the place to fix it.

**Comment by earney** [comment]
I will look into this deeper.  I believe there are issues with both to_bytes and from_bytes.

**Comment by earney** [comment]
Kiko,

If you ran the example above (6 hours ago), your repo must be out of date.  The commits I made last night should have fixed the example you gave.   int.to_bytes is not implemeted yet.  I'll need to look into that asap.  Also the signed variable in int.from_bytes is not implemented yet,   This seems like a short project I can work on the next few days... :)

All of the following (which I got out of the int.from_bytes docs) return the correct results except for the 3rd one:
 
assert int.from_bytes(b'\x00\x10', byteorder='big') == 16
assert int.from_bytes(b'\x00\x10', byteorder='little') == 4096
print(int.from_bytes(b'\xfc\x00', byteorder='big', signed=True))  # <== bad
assert int.from_bytes(b'\xfc\x00', byteorder='big', signed=False) == 64512
assert int.from_bytes([255, 0, 0], byteorder='big') == 16711680

**Comment by kikocorreoso** [comment]
@earney I tested your commit but some stuff with bytes it is not yet correct and the signed kw was not implemented or, at least, this is what I thought. 

If you think all is correct, please, close the issue and it could be reopened if necessary.

**Comment by earney** [comment]
@kikocorreoso Please post some examples of things that do not work.   Maybe I haven't tested those.

Billy

**Comment by kikocorreoso** [comment]
The following in Brython (dev version updated few minutes ago):

```python
kk = b'\xfc'
print(kk)
print(int.from_bytes(kk, 'big'))
```

results in the following:

```
b'\xc3\xbc'
50108
```

In Python (3.4) the results are:
```
b'\xfc'
252
```

I think the problem is just how brython is converting from bytes literals (`b'xxxxxxx'`) to `bytes` or `bytearray`. That conversion is wrong.

Also, using a `bytearray` inside `int.from_bytes` throws an error:
```
kk = bytearray([252,0])
int.from_bytes(kk, 'big')
```
returns
```
TypeError: _bytes is undefined
  module '__main__' line 3
print(int.from_bytes(kk, 'big'))
  module '__main__' line 3
print(int.from_bytes(kk, 'big'))
```

Thanks

**Comment by earney** [comment]
I don't think brython.js has been updated in the repo.  I have updated it,
and pushed it to the repo. (That should fix the first issue you raised.)

The bytearray issue seems valid.  I remade the int.from_bytes function and
I don't think I've written the code for bytearray.

Billy

**Comment by earney** [comment]
@kikocorreoso,  I believe this has been resolved.   Please reopen or open a new issue if you find other examples that do not work.

**Comment by kikocorreoso** [comment]
@earney the localhost ***site/tests/editor.html*** page don't use ***bython.js*** file so that is no related.

So, the following is still not working (repo updated some minutes ago):

>The following in Brython (dev version updated few minutes ago):

>`kk = b'\xfc'`

>`print(kk)`

>`print(int.from_bytes(kk, 'big'))`

>results in the following:

>`b'\xc3\xbc'`

>`50108`

>In Python (3.4) the results are:

>`b'\xfc'`

>`252`

>I think the problem is just how brython is converting from bytes literals (b'xxxxxxx') to bytes or >bytearray. That conversion is wrong.

The `bytearray` issue on `int.from_bytes` is solved (thanks!) and the inclusion of the `signed` keyword make it more compliant with Cpython3 (thanks!).

**Comment by earney** [comment]
Wow!!  Now here is something odd..

Try running

print(b'\xfc')
print(int.from_bytes(b'\xfc', 'big'))

at site/tests/index.html  and site/tests/editor.html.   index.html returns
the expected (correct) results, while site/tests/editor.html returns the
incorrect results kiko points out above.   The only 'real' difference I see
is that py_VFS.js is being imported in editor.html but when I comment that
portion out, I still get the same inconsistent results.

Can any of you duplicate this? If so,  any ideas why this is occurring?

**Comment by earney** [comment]
charset of editor.html is UTF-8
charset of index.html is windows-1252

This is interesting..  How should we resolve this, because this could cause
some major confusion, like it has for @kikocorreoso and myself! :)

**Comment by earney** [comment]
I got this working consistently by doing the following when the brython
parser sees the byte shorthand b'.....':

b'.....' is converted to bytes(.... , 'ISO-8859-1')

I believe this will convert things properly.

**Comment by kikocorreoso** [comment]
I  obtain correct results on 'index.html' and 'editor.html'. Thanks for the time. I was digging with no luck. You're a master, Billy. Thanks.

I close the issue.

**Comment by earney** [comment]
I'm no master.  I want to thank you for your patience and understanding!  I
would have never guess that the same code would produce different results
on different pages (editor.html vs index.html), that is why I kept saying
make sure your source is up to date.  I guess I should have tried to run it
on editor.html too!

Billy
